version: "3.7"

services:
    flask:
        build: ./app
        ports:
            - 5010:5000
        restart:
            always
        
    mysql:
        image: mysql
        ports: 
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

        volumes: 
            - ./app/src/db-init/:/docker-entrypoint-initdb.d/

    
    adminer:
        image: adminer
        ports:
            - 8080:8080
